Feature/map select
Bronsun/med-fe pull request #3
Opened 2022-07-17 14:09 UTC by Bronsun

2022-07-17 15:55 UTC, ZuzaTwardowska requested changes

2022-07-17 15:55 UTC, ZuzaTwardowska commented on components/Molecules/PopupMarker.tsx
> +import ClinicModel from "../../models/ClinicModel";
wtf is this file

2022-07-17 15:55 UTC, ZuzaTwardowska commented on components/Organisms/MainSearcher.tsx
> +        <InputComponent
a tu zostaje input?

2022-07-17 15:55 UTC, ZuzaTwardowska commented on components/Organisms/MainSearcher.tsx
>            <InputComponent
o ten input tez

2022-07-17 15:55 UTC, ZuzaTwardowska commented on components/Organisms/MainSearcher.tsx
>            <InputComponent
i ten

2022-07-17 15:55 UTC, ZuzaTwardowska commented on components/Organisms/MainSearcher.tsx
>            <InputComponent
i ten

2022-07-17 15:55 UTC, ZuzaTwardowska commented on components/Organisms/MainSearcher.tsx
>            <InputComponent
ten ok

2022-07-17 15:55 UTC, ZuzaTwardowska commented on components/Organisms/Map.tsx
> +
how many new lines can you put?

2022-07-17 15:55 UTC, ZuzaTwardowska commented on components/Organisms/Map.tsx
> +
enter enter

2022-07-17 15:55 UTC, ZuzaTwardowska commented on components/Organisms/Map.tsx
> +
no zebys jeszcze normalnego entera na klawiaturze mial

2022-07-17 15:55 UTC, ZuzaTwardowska commented on pages/clinics.tsx
> +
entery w pliku

2022-07-17 15:55 UTC, ZuzaTwardowska commented on pages/clinics.tsx
> +          <MyMap clinicsList={clinicsList}/></div>
na cholere jej cala lista a nie same lokalizacje?

2022-07-17 15:55 UTC, ZuzaTwardowska commented on styles/ClinicsStyles.scss
> +    border-radius: 10px;
tabulator to co?

2022-07-17 15:55 UTC, ZuzaTwardowska commented on styles/ClinicsStyles.scss
> +
enter

2022-07-17 15:55 UTC, ZuzaTwardowska commented on styles/ClinicsStyles.scss
> +
enter

2022-07-17 15:55 UTC, ZuzaTwardowska commented on styles/ClinicsStyles.scss
> +
enter

2022-07-17 15:55 UTC, ZuzaTwardowska commented on styles/ClinicsStyles.scss
> +    width: 30vw;
vw surprisingly?

2022-07-20 08:04 UTC, Bronsun commented on components/Molecules/PopupMarker.tsx
> +import ClinicModel from "../../models/ClinicModel";
No twój model XD

2022-07-20 08:04 UTC, Bronsun commented on components/Organisms/MainSearcher.tsx
>            <InputComponent
Inputy będą zmienione w drugim tasku, muszę backend poprawić

2022-07-20 08:05 UTC, Bronsun commented on components/Organisms/MainSearcher.tsx
>            <InputComponent
Nie

2022-07-20 08:08 UTC, Bronsun commented on styles/ClinicsStyles.scss
> +    border-radius: 10px;
Jajco XD

2022-07-20 18:29 UTC, ZuzaTwardowska commented on styles/ClinicsStyles.scss
>  @import "colorTheme";
co to są za zmiany w tym pliku? czemu az tyle? zrob porządnego merga z developem i porozwiązuj konflikty

2022-07-20 18:31 UTC, ZuzaTwardowska commented on components/Molecules/PopupMarker.tsx
> +  const parseLengthOfTheQueue = (value: number) => {
to jest w utilities - zrob merge z developem, nie masz aktualnej wersji kodu tylko kod sprzed dwóch tygodni

2022-07-20 18:33 UTC, ZuzaTwardowska commented on components/Organisms/MainSearcher.tsx
> +        <InputComponent
ponawiam

2022-07-22 17:30 UTC, Bronsun commented
Zajebiście Mati zrobiłeś ESSA

2022-07-22 17:31 UTC, merged